# Generated by Django 5.2.7 on 2025-10-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlJourney', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LearningExperience',
            new_name='LearningJourney',
        ),
    ]
